set-option -g prefix C-a
set-option -g default-shell /usr/bin/zsh

unbind-key C-b
bind-key C-a send-prefix


set -g base-index 1
setw -g pane-base-index 1


set -g status-bg black
set -g status-fg white
set -g status-left '#[fg=green]#H #[fg=yellow]#(date "+%Y-%m-%d %H:%M")'
set -g status-justify centre


bind-key | split-window -h
bind-key - split-window -v


set -g mouse on

## auto copy & paste

# vi mode
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi 'v' send-keys -X begin-selection
bind-key -T copy-mode-vi 'y' send-keys -X copy-pipe-and-cancel "xclip -in -selection clipboard"
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe "xclip -in -selection clipboard"


# usage panel
set -g status-right '#[fg=cyan]#(nvidia-smi --query-gpu=utilization.gpu,memory.used --format=csv,noheader,nounits | awk -F, '\''{gpu_sum+=$1; if($2>mem_max) mem_max=$2; gpu_count++} END {print "GPU Avg:" gpu_sum/gpu_count "% Mem Max:" mem_max "MB"}'\'')'
